# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import masrpc_pb2 as masrpc__pb2

GRPC_GENERATED_VERSION = '1.65.4'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in masrpc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class MasRPCStub(object):
    """The MasRPC service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Load = channel.unary_unary(
                '/masrpc.MasRPC/Load',
                request_serializer=masrpc__pb2.LoadRequest.SerializeToString,
                response_deserializer=masrpc__pb2.OperationResponse.FromString,
                _registered_method=True)
        self.Send = channel.unary_unary(
                '/masrpc.MasRPC/Send',
                request_serializer=masrpc__pb2.SendRequest.SerializeToString,
                response_deserializer=masrpc__pb2.OperationResponse.FromString,
                _registered_method=True)
        self.GetLog = channel.unary_unary(
                '/masrpc.MasRPC/GetLog',
                request_serializer=masrpc__pb2.GetLogRequest.SerializeToString,
                response_deserializer=masrpc__pb2.OperationResponse.FromString,
                _registered_method=True)
        self.UpdateActor = channel.unary_unary(
                '/masrpc.MasRPC/UpdateActor',
                request_serializer=masrpc__pb2.UpdateActorRequest.SerializeToString,
                response_deserializer=masrpc__pb2.UpdateActorResponse.FromString,
                _registered_method=True)


class MasRPCServicer(object):
    """The MasRPC service definition.
    """

    def Load(self, request, context):
        """Load function
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Send(self, request, context):
        """Send function
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLog(self, request, context):
        """GetLog function
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateActor(self, request, context):
        """UpdateActor function
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MasRPCServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Load': grpc.unary_unary_rpc_method_handler(
                    servicer.Load,
                    request_deserializer=masrpc__pb2.LoadRequest.FromString,
                    response_serializer=masrpc__pb2.OperationResponse.SerializeToString,
            ),
            'Send': grpc.unary_unary_rpc_method_handler(
                    servicer.Send,
                    request_deserializer=masrpc__pb2.SendRequest.FromString,
                    response_serializer=masrpc__pb2.OperationResponse.SerializeToString,
            ),
            'GetLog': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLog,
                    request_deserializer=masrpc__pb2.GetLogRequest.FromString,
                    response_serializer=masrpc__pb2.OperationResponse.SerializeToString,
            ),
            'UpdateActor': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateActor,
                    request_deserializer=masrpc__pb2.UpdateActorRequest.FromString,
                    response_serializer=masrpc__pb2.UpdateActorResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'masrpc.MasRPC', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('masrpc.MasRPC', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MasRPC(object):
    """The MasRPC service definition.
    """

    @staticmethod
    def Load(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/masrpc.MasRPC/Load',
            masrpc__pb2.LoadRequest.SerializeToString,
            masrpc__pb2.OperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Send(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/masrpc.MasRPC/Send',
            masrpc__pb2.SendRequest.SerializeToString,
            masrpc__pb2.OperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/masrpc.MasRPC/GetLog',
            masrpc__pb2.GetLogRequest.SerializeToString,
            masrpc__pb2.OperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateActor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/masrpc.MasRPC/UpdateActor',
            masrpc__pb2.UpdateActorRequest.SerializeToString,
            masrpc__pb2.UpdateActorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
